name: Lint Files
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Frontend lint check
        working-directory: ./frontend
        run: |
              npm ci
              npm run lint
